# Generated by Django 3.2.6 on 2021-08-15 07:42

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('des', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
