# Generated by Django 3.2.6 on 2021-08-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20210818_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='product_id',
            new_name='product',
        ),
    ]
