# Generated by Django 3.2.6 on 2021-08-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_rename_product_id_user_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
    ]
