# Generated by Django 3.2.6 on 2021-08-19 08:27

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_remove_user_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Shoe', max_length=25)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('des', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Shoe',
            },
        ),
    ]
