# Generated by Django 3.2.6 on 2021-08-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
