# Generated by Django 3.2.6 on 2021-08-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_remove_user_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
