# Generated by Django 3.2.6 on 2021-08-19 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 19, 13, 9, 2, 532515)),
        ),
        migrations.AddField(
            model_name='user',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
