# Generated by Django 3.2.6 on 2021-08-20 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20210819_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_id',
            field=models.CharField(default='no', max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 6, 35, 34, 795044)),
        ),
    ]
