# Generated by Django 3.2.6 on 2021-08-20 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20210820_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 6, 42, 34, 852784)),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Customer',
        ),
    ]
