# Generated by Django 3.2.6 on 2021-08-21 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 9, 13, 59, 166631, tzinfo=utc)),
        ),
    ]
