# Generated by Django 3.2.6 on 2021-08-21 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_alter_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Shoe', max_length=25)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('des', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Dress',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 12, 33, 14, 456360, tzinfo=utc)),
        ),
    ]
