# Generated by Django 3.2.6 on 2021-08-21 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_auto_20210821_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Bag', max_length=25)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('des', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Bag',
            },
        ),
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(default='Dress', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 13, 26, 52, 431270, tzinfo=utc)),
        ),
    ]
