# Generated by Django 3.2.6 on 2021-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default='2021/23/08/22/21, 12:23:05'),
        ),
    ]
