# Generated by Django 3.2.6 on 2021-08-22 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 13, 7, 32, 573101, tzinfo=utc)),
        ),
    ]
