# Generated by Django 3.2.6 on 2021-08-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_alter_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='des',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='razmer',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
