# Generated by Django 3.2.6 on 2021-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0030_auto_20210828_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='des',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='des',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='title',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='des',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='title',
        ),
        migrations.AddField(
            model_name='bag',
            name='brand',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bag',
            name='model',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bag',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bag',
            name='razmer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='dress',
            name='brand',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dress',
            name='model',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dress',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dress',
            name='razmer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shoe',
            name='razmer',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
