# Generated by Django 3.2.6 on 2021-08-28 17:18

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0031_auto_20210828_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hijab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Shoe', max_length=25)),
                ('brand', models.CharField(blank=True, max_length=15)),
                ('model', models.CharField(blank=True, max_length=15)),
                ('razmer', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Hijab',
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Shoe', max_length=25)),
                ('brand', models.CharField(blank=True, max_length=15)),
                ('model', models.CharField(blank=True, max_length=15)),
                ('razmer', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Treasure',
            },
        ),
    ]
