# Generated by Django 3.2.6 on 2021-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0032_hijab_treasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijab',
            name='category',
            field=models.CharField(default='Hijab', max_length=25),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='category',
            field=models.CharField(default='Treasure', max_length=25),
        ),
    ]
