# Generated by Django 3.2.6 on 2021-09-01 15:33

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0033_auto_20210828_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Atir', max_length=25)),
                ('brand', models.CharField(blank=True, max_length=15)),
                ('model', models.CharField(blank=True, max_length=15)),
                ('gramm', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Atir',
            },
        ),
        migrations.CreateModel(
            name='Romol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Romol', max_length=25)),
                ('brand', models.CharField(blank=True, max_length=15)),
                ('made', models.CharField(blank=True, max_length=15)),
                ('material', models.CharField(blank=True, max_length=10)),
                ('price', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(upload_to=ecom.models.getpath)),
            ],
            options={
                'db_table': 'Romol',
            },
        ),
    ]
