# Generated by Django 3.2.6 on 2021-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0034_atir_romol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atir',
        ),
        migrations.AlterField(
            model_name='bag',
            name='category',
            field=models.CharField(default='Bag', max_length=45),
        ),
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(default='Dress', max_length=45),
        ),
        migrations.AlterField(
            model_name='hijab',
            name='category',
            field=models.CharField(default='Hijab', max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Product', max_length=45),
        ),
        migrations.AlterField(
            model_name='romol',
            name='category',
            field=models.CharField(default='Romol', max_length=45),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(default='Shoe', max_length=45),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='category',
            field=models.CharField(default='Treasure', max_length=45),
        ),
    ]
