# Generated by Django 3.2.6 on 2021-09-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0035_auto_20210906_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='razmer',
            new_name='color',
        ),
    ]
